ncol = math.random(1, 9)
print("^"..ncol.."[Moonlight]^0 Welcome to the Moonlight Docs^0")
print("#################     Sercurity    #######################")
print("^"..ncol.."[Moonlight] ^0 How to secure my Server?")
print("")
print("You just have to rename the most important triggers of you server files and add the old ones to the anticheat config\n so we can ban the modder")
print("^"..ncol.."[Moonlight] ^0 Is my server safe without anything?")
print("")
print("Yes, but modders can still abuse open source triggers, thats why you should rename them and obfuscate the script")
